
theme = "gruvbox_dark_hard"

[keys.normal]

C-r = ":config-reload"
C-o = ":config-open"

C-s = ":w!"
C-q = ":q!"

A-s = ":u"
A-q = ":bc"

esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]

j = { j = ["normal_mode"] }

[keys.normal.space]

w = ":w"
q = ":q"

space = { c = ":bc" }
