
[manager]

[preview]

[[manager.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[opener]
edit = [
	{ run = 'hx "$@"', block = true },
]

vim = [
	{ run = 'vim "$@"', block = true },
]

play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]

open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

img = [
	{ run = 'imv "$@"', block = true},
  { run = 'feh "$@"', block = true}
]

[open]
rules = [
	{ mime = "text/*", use = ["edit", "nvim"] },
	{ mime = "video/*", use = "play" },
	{ mime = "image/*", use = ["img", "open"] },

	# { mime = "application/json", use = "edit" },
	{ name = "*.json", use = "nvim" },
	{ name = "*.norg", use = "nvim" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
]
